function headerCreator() {
  var head = [
    '<meta charset="UTF-8" />',
    '<meta http-equiv="X-UA-Compatible" content="IE=edge" />',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    '<link rel="stylesheet" href="../css/header.css" />',
    '<link rel="stylesheet" href="../css/site.css" />',
    '<script src="../js/header.js"></script>',
    '<script src="../js/image-viewer.js"></script>',
    '<script src="../js/more.js"></script>',
  ].join("\n");
  var body = [
    '<header id="header">',
    '<nav id="header-nav" class="unselectable">',
    "<ul>",
    '<li class="header-nav-item" id="header-seemore" onclick="more();">',
    "<a>Vedi di più </a>",
    '<img id="img-menu-arrow" src="../images/arrow-down.svg" alt="v" />',
    "</li>",
    '<li class="header-nav-item">',
    '<img src="../images/empty-icon.svg" />',
    "<a>Eolica</a>",
    "</li>",
    '<li class="header-nav-item">',
    '<img src="../images/empty-icon.svg" />',
    "<a>Idroelettrica</a>",
    "</li>",
    '<li class="header-nav-item">',
    '<img src="../images/empty-icon.svg" />',
    "<a>Solare</a>",
    "</li>",
    '<li class="header-nav-item">',
    '<img src="../images/empty-icon.svg" />',
    "<a>Geotermica</a>",
    "</li>",
    '<li class="header-nav-item">',
    '<img src="../images/empty-icon.svg" />',
    "<a>Nucleare</a>",
    "</li>",
    '<li class="header-nav-item">',
    '<img src="../images/empty-icon.svg" />',
    "<a>Combustione fossile</a>",
    "</li>",
    "</ul>",
    '<img id="header-logo" />',
    '<button id="header-language-button">',
    "</button>",
    '<button id="header-theme-button">',
    "</button>",
    "</nav>",
    "</header>",
  ].join("\n");
  $("body").append(body);
  $("head").append(head);
}
